### ISSUE TITLE
Xdg-open was not found ? 

### ISSUE THREAD

**Issue by vsedov** [loganswartz/updoc.nvim#1]
The mistake Could be found on line  https://github.com/loganswartz/updoc.nvim/blob/ef7aa8c35a174bdb2e8909a7bacc0520096b04a4/lua/updoc/utils.lua#L53 ? 

```
Tried to open 'https://pypi.org/search/?q=list', but 'xdg-open' was not found.
```
When I do have it installed 

Also nice plugin

**Comment by loganswartz** [comment]
Yep, I actually just came across this myself as well, I'll have the fix pushed soon.
